name: Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "This wasn't supposed to happen..."
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Do this '...'
        2. Do that '....'
        3. Do more '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "It was supposed to do this..."
    validations:
      required: false

  - type: textarea
    id: desktop
    attributes:
      label: Setup Information
      description: Explain what environment you encountered the problem in and what ecosystem you were connecting to.
      placeholder: "OS: Windows 10, Browser: Chrome, Version: 90.0.4430.212, Manipulators: Sensapex uMp Micromanipulators"
    validations:
      required: false

  - type: dropdown
    id: plan
    attributes:
      label: Do you plan to solve this issue yourself?
      options:
        - "Yes"
        - "No"
        - "I need help"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false